import { Button, HorizontalBox, TextEdit, ComboBox } from "std-widgets.slint";

export struct MedioPagoSt{
    id: int,
    medio: string,
}
export struct PagoSt {
    int_id: int,
    monto: float,
    pagado: float,
}
export component PagoComp inherits Rectangle{
    in-out property <PagoSt> pago;
    in-out property <bool> pagado;
    in-out property <[string]> medios;

    HorizontalBox {
        text:=TextEdit {            
            text: "\{root.pago.monto}";   
            padding: 0px;
            font-size: 10px;
            height: 37px;
            
            enabled: !pagado;
        }
        box := ComboBox {
            enabled: !pagado;
            padding: 0px;
            height: 37px;
            width: 100px;
            model: medios;
            current-value: "first";
            
        }
        if pagado: Button {text:"Borrar";clicked => { root.pago = {monto:370}; }}
        if !pagado: Button {text:"Cash";clicked=>{root.pago = {monto: 30}}}
    }
}