[package]
name = "memory"
version = "0.1.0"
authors = ["Lucas Igarzabal <igarzaballucas@hotmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.203"
slint = "1.6"
sqlx = { version= "0.7.4", features = ["sqlite", "runtime-tokio", "tls-rustls", "sqlx-macros", "chrono"] }
chrono = {version= "0.4.38" ,features = ["serde"] }
thiserror = "1.0.61"
[build-dependencies]
slint-build = "1.6"
