//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "caja")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub inicio: String,
    pub cierre: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub monto_inicio: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub monto_cierre: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub ventas_totales: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
