//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use chrono::NaiveDateTime;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "caja")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub inicio: NaiveDateTime,
    pub cierre: Option<NaiveDateTime>,
    #[sea_orm(column_type = "Double")]
    pub monto_inicio: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub monto_cierre: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub ventas_totales: f64,
    pub cajero: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
