//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod caja;
pub mod cliente;
pub mod codigo_barras;
pub mod config;
pub mod medio_pago;
pub mod pago;
pub mod pesable;
pub mod producto;
pub mod proveedor;
pub mod relacion_prod_prov;
pub mod relacion_venta_pes;
pub mod relacion_venta_prod;
pub mod relacion_venta_rub;
pub mod rubro;
pub mod user;
pub mod venta;
