//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use chrono::NaiveDateTime;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "pesable")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub codigo: i64,
    #[sea_orm(column_type = "Double")]
    pub precio_peso: f64,
    #[sea_orm(column_type = "Double")]
    pub porcentaje: f64,
    #[sea_orm(column_type = "Double")]
    pub costo_kilo: f64,
    pub descripcion: String,
    pub updated_at: NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
