//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::caja::Entity as Caja;
pub use super::codigo_barras::Entity as CodigoBarras;
pub use super::config::Entity as Config;
pub use super::medio_pago::Entity as MedioPago;
pub use super::pago::Entity as Pago;
pub use super::pesable::Entity as Pesable;
pub use super::producto::Entity as Producto;
pub use super::proveedor::Entity as Proveedor;
pub use super::relacion_prod_prov::Entity as RelacionProdProv;
pub use super::relacion_venta_pes::Entity as RelacionVentaPes;
pub use super::relacion_venta_prod::Entity as RelacionVentaProd;
pub use super::relacion_venta_rub::Entity as RelacionVentaRub;
pub use super::rubro::Entity as Rubro;
pub use super::user::Entity as User;
pub use super::venta::Entity as Venta;
