//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::caja as CajaDB;
pub use super::cliente as CliDB;
pub use super::codigo_barras as CodeDB;
pub use super::config as ConfDB;
pub use super::deuda as DeudaDB;
pub use super::medio_pago as MedioDB;
pub use super::movimiento as MovDB;
pub use super::pago as PagoDB;
pub use super::pesable as PesDB;
pub use super::producto as ProdDB;
pub use super::proveedor as ProvDB;
pub use super::relacion_prod_prov as ProdProvDB;
pub use super::relacion_venta_pes as VentaPesDB;
pub use super::relacion_venta_prod as VentaProdDB;
pub use super::relacion_venta_rub as VentaRubDB;
pub use super::rubro as RubDB;
pub use super::user as UserDB;
pub use super::venta as VentaDB;
