//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "rubro")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub codigo: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub monto: Option<f64>,
    pub descripcion: String,
    pub updated_at: NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
