//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "deuda")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cliente: i32,
    #[sea_orm(column_type = "Double")]
    pub monto: f32,
    pub pago: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cliente::Entity",
        from = "Column::Cliente",
        to = "super::cliente::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Cliente,
    #[sea_orm(
        belongs_to = "super::pago::Entity",
        from = "Column::Pago",
        to = "super::pago::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Pago,
}

impl Related<super::cliente::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cliente.def()
    }
}

impl Related<super::pago::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pago.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
