import { Button, VerticalBox } from "std-widgets.slint";
import { Pago } from "pago.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    property <int> name;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Pago {
            
        }
    }
}
