import { Button, VerticalBox } from "std-widgets.slint";
import { }
export global Logic {

}
export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.pago = { monto:54.1 }
            }
        }
        
    }
}
