import { Button, VerticalBox } from "std-widgets.slint";
import { Pago } from "pago.slint";
import { PagoSt } from "pago.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    property <PagoSt> pago: { monto: 43.2 };
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                pago = {monto:54.1}
            }
        }
        Pago {
            pago: pago;
        }
    }
}
