import { Button, VerticalBox } from "std-widgets.slint";
import { Pago } from "pago.slint";
import { Logic } from "logic.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                Logic.pagar(1,2)
            }
        }
        
    }
}
