import { Button, HorizontalBox, TextEdit, ComboBox } from "std-widgets.slint";
export struct PagoSt {
    monto: int,
}
export component Pago {
    in-out property <PagoSt> pago;
    HorizontalBox {
        TextEdit {
            text: "/{root.monto}";
        }
        ComboBox {
            y: 0px;
            width: self.preferred-width;
            height: self.preferred-height;
            model: ["first", "second", "third"];
            current-value: "first";
        }
    }
}