import { Button, HorizontalBox, TextEdit, ComboBox } from "std-widgets.slint";
export component Pago {
    in-out property <int> monto;
    in-out property <[int]> name;
    HorizontalBox {
        TextEdit {
            text: "/{root.monto}";
        }
        ComboBox {
            y: 0px;
            width: self.preferred-width;
            height: self.preferred-height;
            model: ["first", "second", "third"];
            current-value: "first";
        }
    }
}