import { VerticalBox } from "std-widgets.slint";
import { Pago, PagoSt } from "pago.slint";

export component Pagos inherits Rectangle {
    in-out property <[PagoSt]> pagos: [{monto: 30, pagado: 30, int_id: 30},{monto:30.1, pagado: 30,int_id:35}];
    in-out property <int> monto:350;
    VerticalBox {
        width: 300px;
        for pay in root.pagos: my-pagos := Pago {
            width: 300px;
            pago: pay;
        }
        Pago {
            pago: {monto:monto,pagado:0};
        }
    }
}
