import { VerticalBox } from "std-widgets.slint";
import { Pago, PagoSt } from "pago.slint";

export component Pagos inherits Rectangle{
    in-out property <[PagoSt]> pagos: [{monto:30.0, id:1.1, pagado: 30.0},{monto:51.2, id:2.4, pagado:51.2}];
    VerticalBox {
        width: 300px;
        for pay in root.pagos: my-pagos := Pago {
            width: 300px;
            pago: pay;
        }
    }
}