import { Button, HorizontalBox, TextEdit, ComboBox } from "std-widgets.slint";
export struct MedioPagoSt{
    id: int,
    medio: string,
}
export struct PagoSt {
    monto: int,
    id: int
}
export component Pago inherits Rectangle{
    in-out property <PagoSt> pago;
    HorizontalBox {
        TextEdit {
            text: "\{root.pago.monto} a";
        }
        ComboBox {
            padding: 5px;
            height: 40px;
            width: self.preferred-width;
            model: ["first", "second", "third"];
            current-value: "first";
        }
        Button {
            text: "Cash";
            clicked => { root.pago = {monto: 20}; }
        }
    }
}