import { Button, HorizontalBox, TextEdit, ComboBox, LineEdit } from "std-widgets.slint";
import { Logic } from "../logic.slint";
import { PagoSt } from "../structs.slint";



export component Pago inherits Rectangle{
    in-out property <PagoSt> pago;
    in-out property <bool> pagado;
    in-out property <[string]> medios;
    in-out property <string> text;
    callback call();
    callback pagar()->string;
    
    function borrar(){
        Logic.test("Borrado")
    }

    HorizontalBox {
        text:= LineEdit {            
            text: "\{root.pago.monto}";   
            padding: 0px;
            font-size: 10px;
            height: 37px;
            accepted(dato) => {self.text=pagar()}
            enabled: !pagado;
        }
        box := ComboBox {
            enabled: !pagado;
            padding: 0px;
            height: 37px;
            width: 100px;
            model: medios;
            current-value: "first";
            
        }
        if pagado: Button {text:"Borrar";clicked => { borrar() }}
        if !pagado: Button {text:"Cash";clicked=>{ text.text = pagar() }}
    }
}