import { Button, VerticalBox, HorizontalBox, GridBox, TabWidget, StandardTableView } from "std-widgets.slint";
import { Logic } from "logic.slint";
import { Pagos } from "main-pagos.slint";
import { UserFND,ClienteFND } from "structs.slint";
import { Login } from "login.slint";
import { TablaProductos } from "main-tabla-productos.slint";
export { Logic }
export component App inherits Window {
    in-out property<int> counter: 42;
    in-out property <bool> logged:false;
    in-out property <string> window:"Main";
    in-out property <ClienteFND> reg;
    callback request-increase-value();
    
    if window == "Main":
    main:=VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value()
            }
        }
        TablaProductos {vals: [{descripcion:"Producto1",precio:1.2},{descripcion:"Producto2",precio:201}];}
        Pagos {}
    }
    if window == "Login":
    login:=Login {}

}
