import { Button, VerticalBox } from "std-widgets.slint";
import { Logic } from "logic.slint";
import { Pagos } from "pagos.slint";
export { Logic }
export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback request-increase-value();
    
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Pagos {}
    }
}
