export struct MedioPagoSt{
    id: int,
    medio: string,
}
export struct PagoSt {
    int_id: int,
    monto: float,
    medio_pago: MedioPagoSt,
    pagado: float,
}
export struct VentaSt{
    id: int,
    monto_total: float,
    pagos: [PagoSt],
    monto_pagado: float,
    paga: bool,
    cerrada: bool,
    time: string,
}

export global Logic{
    pure callback pagar(int,int)->int;
    pure callback test(string);
    pure callback get_venta_actual(bool)->VentaSt;
    pure callback open_login();
    pure callback try_login()->bool;
}