import { Button, HorizontalBox, TextEdit, ComboBox, LineEdit } from "std-widgets.slint";
import { Logic } from "logic.slint";
import { PagoFND } from "structs.slint";



export component Pago inherits Rectangle{
    in-out property <PagoFND> pago;
    in property <bool> pagado;
    in property <[string]> medios;
    in property <string> text;
    property <string> medio_act;
    callback call();
    callback pagar()->string;
    callback set_medio();
    
    function borrar(){
        Logic.test("Borrado")
    }
    
    HorizontalBox {
        text:= LineEdit {            
            text: "\{root.pago.monto}";   
            width: 150px;
            padding: 0px;
            font-size: 10px;
            height: 37px;
            accepted(dato) => {self.text=pagar()}
            enabled: !pagado;
        }
        if pagado:box := ComboBox {
            enabled: !pagado;
            padding: 0px;
            height: 37px;
            width: 100px;
            model: medios;
            current-value: pago.medio-pago.medio;
        }
        if !pagado:box2 := ComboBox{
            enabled: !pagado;
            padding: 0px;
            height: 37px;
            width: 100px;
            model: medios;
            current-value: medios[0];
        }
        if pagado: Button {width:60px;text:"Borrar";clicked => { borrar() }}
        if !pagado: Button {width:50px;text:"Cash";clicked=>{ text.text = pagar() }}
    }
}