import { VerticalBox } from "std-widgets.slint";
import { Logic } from "logic.slint";
import { PagoFND } from "structs.slint";
import { Pago } from "main-pago.slint";

export component Pagos inherits Rectangle {
    in-out property <[PagoFND]> pagos: [{monto: 30.0, pagado: 30.0, int_id: 30},{monto:30.0, pagado: 30.0,int_id:35}];
    in property <[string]> medios;
    in-out property <float> monto:350;
    in-out property <float> pagado:0;
    VerticalLayout {
        width: root.width;
        for pay in root.pagos: my-pagos := Pago {
            width: root.width - 15px;
            pago: pay;
            pagado: true;
            medios: medios;
        }
        Pago {
            pagar => {Logic.pagar(1,self.text.to-float());
            pagos=pagos;
            "\{root.monto - root.pagado}"}
            width: root.width - 15px;
            pagado: false;
            medios: medios;
            pago: {monto:monto - pagado,pagado:0};
        }
    }
}
