import {  HorizontalBox, ListView, VerticalBox, StandardTableView } from "std-widgets.slint";
import { ValFND } from "structs.slint";

export component TablaProductos {
    in-out property <[ValFND]> productos;
    VerticalLayout {
        HorizontalLayout {
            height: 18px;

            Text {
                height: 9px;
                text: "Producto";
            }
            Text {
                horizontal-alignment: right;
                height: 9px;
                text: "Precio";
            }
        }
        ListView {
            width: parent.width;
            for val[i] in productos: valuables:=HorizontalBox{
                width: parent.width+7px;
                Text {
                    height: 9px;
                    text: val.descripcion;
                }
                Text {
                    horizontal-alignment: right;
                    height: 9px;
                    text: val.precio;
                }
            }
        }
    }
}