import { LineEdit, HorizontalBox, ComboBox } from "std-widgets.slint";
import { ClienteFND } from "structs.slint";
export component Header {
    in-out property <[string]> clientes;
    HorizontalBox{
        width: 98%;
        height: 70px;
        
        search:=LineEdit {
            height: 30px;
            width: 200px;
            placeholder-text: "Buscar..";
        }
        Text {
            horizontal-alignment: center;
            height: 30px;
            vertical-alignment: center;
            text: "Cajero: Nombre del Cajero";
        }
        Text {
            horizontal-alignment: right;
            height: 30px;
            vertical-alignment: center;
            text: "Cliente: ";}
        ComboBox {
            width: 200px;
            height: 30px;
            model: clientes;
        }
    }
}