 import { StandardTableView, TabWidget, VerticalBox } from "std-widgets.slint";
import { TablaProductos } from "main-tabla-productos.slint";
import { Pagos } from "main-pagos.slint";
import { Logic } from "logic.slint";
export component SideBar {
    VerticalLayout{
        TabWidget {
            padding: 0px;
            width: 300px;
            resumen:=Tab{
                title: "Resumen de venta";
                VerticalBox {
                    width: parent.width;
                    TablaProductos {
                        width: parent.width;
                    }                
                }
            }
            ventas:=Tab{
                title: "Ventas";
                //ventas anteriores
            }
        }
        VerticalLayout {
            Pagos {
                width: parent.width;
            }
            Text {
                width: parent.width;
                horizontal-alignment: TextHorizontalAlignment.right;
                text: "Total: \{Logic.venta.monto-total - Logic.venta.monto-pagado}";
            }
        }
    }
}