import { VentaFND } from "structs.slint";
import { GridBox, VerticalBox, TabWidget } from "std-widgets.slint";
import { Header } from "main-header.slint";
import { CuadroVenta } from "main-venta.slint";
import { SideBar } from "main-sidebar.slint";
export component Principal {
    in-out property <[VentaFND]> ventas;
    in property <[string]> medios;
    VerticalBox {
        spacing: 0;
        Header {
            clientes: medios;
        }
        TabWidget {
            width: 100%;
            Tab{
                title: "Venta A";
                HorizontalLayout {
                    CuadroVenta {
                        horizontal-stretch: 1;
                        venta: ventas[0];
                    }
                    SideBar {
                        medios: medios;
                        venta: ventas[0];
                        width: 450px;
        
                    }
                }
            }
            Tab{
                title: "Venta B";
                HorizontalLayout {
                    CuadroVenta {
                        horizontal-stretch: 1;
                        venta: ventas[1];
                    }
                    SideBar {
                        medios: medios;
                        venta: ventas[1];
                        width: 450px;
        
                    }
                }
            }
        }
    }
    
}