import { StandardTableView, TabWidget, VerticalBox } from "std-widgets.slint";
import { TablaProductos } from "main-tabla-productos.slint";
import { VentaFND } from "structs.slint";
import { Pagos } from "main-pagos.slint";
import { Logic } from "logic.slint";
export component SideBar {
    in-out property <VentaFND> venta;
    in property <[string]> medios;
    
    VerticalLayout{
        width: 250px;
        TabWidget {
            padding: 0px;
            width: parent.width;
            resumen:=Tab{
                title: "Resumen de venta";
                VerticalBox {
                    width: parent.width;
                    TablaProductos {
                        width: parent.width;
                        productos: venta.productos;
                    }                
                }
            }
            ventas:=Tab{
                title: "Ventas";
                //ventas anteriores
            }
        }
        VerticalLayout {
            Pagos {
                pagos: venta.pagos;
                width: parent.width;
                medios: medios;
            }
            Text {
                width: parent.width;
                horizontal-alignment: TextHorizontalAlignment.right;
                text: "Total: \{venta.monto-total - venta.monto-pagado}";
            }
        }
    }
}