import { VerticalBox } from "std-widgets.slint";
import { Logic } from "logic.slint";
import { PagoFND } from "structs.slint";
import { Pago } from "main-pago.slint";

export component Pagos inherits Rectangle {
    in-out property <[PagoFND]> pagos: [{monto: 30.0, pagado: 30.0, int_id: 30},{monto:30.0, pagado: 30.0,int_id:35}];
    
    in-out property <float> monto:350;
    in-out property <float> pagado:0;
    VerticalBox {
        width: root.width - 10px;
        for pay in root.pagos: my-pagos := Pago {
            
            width: root.width - 15px;
            pago: pay;
            pagado: true;
            medios: ["first", "second", "third"];
            
        }
        Pago {
            pagar => {Logic.pagar(1,self.text.to-float());
            pagos=[{monto:30.0,pagado:30.0,int_id:30},{monto:45.0,pagado:30.0,int_id:20},{monto:10.0,pagado:10.0,int_id:10}];
            "\{root.monto - root.pagado}"}
            width: root.width - 15px;
            pagado: false;
            medios: ["first", "second"];
            pago: {monto:monto - pagado,pagado:0};
        }
    }
}
