import { VerticalBox } from "std-widgets.slint";
import { PagoSt , Pago } from "pago.slint";

export component Pagos inherits Rectangle {
    in-out property <[PagoSt]> pagos: [{monto: 30.0, pagado: 30.0, int_id: 30},{monto:30.0, pagado: 30.0,int_id:35}];
    in-out property <int> monto:350;
    
    VerticalBox {
        width: 300px;
        for pay in root.pagos: my-pagos := Pago {
            width: 300px;
            pago: pay;
            pagado: true;
            medios: ["first", "second", "third"];
            
        }
        Pago {
            width: 300px;
            pagado: false;
            medios: ["first", "second"];
            pago: {monto:monto,pagado:0};
        }
    }
}
