export struct CajaFND{
    id: int,
    inicio: string,
    cierre: string,
    ventas_totales: float,
    monto_inicio: float,
    monto_cierre: float,
    cajero: string,
    totales: [float],
    medios: [string],
}
export struct CuentaFND{
    auth:bool,
    cuenta:float,
}
export struct ClienteFND{
    id: int,
    nombre: string,
    dni: int,
    activo: bool,
    created: string,
    limite: CuentaFND,
    regular:bool,
}
export struct ConfigFND {
    politica_redondeo: float,
    formato_producto: string,
    modo_mayus: string,
    cantidad_productos: int,
    medios: [string],
}
export struct MedioPagoFND{
    id: int,
    medio: string,
}
export struct PagoFND {
    int_id: int,
    monto: float,
    medio_pago: MedioPagoFND,
    pagado: float,
}
export struct ProveedorFND {
    id: int,
    nombre: string,
    contacto: int,
}
export struct ValFND{
    id:int,
    codigo:int,
    descripcion: string,
    precio: float,
    cantidad: float,
}
export struct UserFND{
    id: string,
    nombre:string,
    rango: string,
}
export struct VentaFND{
    id: int,
    monto-total: float,
    productos: [ValFND],
    pagos: [PagoFND],
    monto-pagado: float,
    user: UserFND,
    cliente: ClienteFND,
    paga: bool,
    cerrada: bool,
    time: string,
}
export struct RelProdProvFND{
    proveedor: int,
    codigo: int,
}

export struct ProductoFND{
    id: int,
    codigos_de_barras: [int],
    precio_de_venta: float,
    porcentaje: float,
    precio_de_costo: float,
    tipo_producto: string,
    marca: string,
    variedad: string,
    presentacion: string,
    proveedores: [RelProdProvFND]
}

export struct RubroFND {
    id: int,
    codigo: int,
    monto: float,
    descripcion: string,
}

export struct PesableFND {
    id: int,
    codigo: int,
    precio_peso: float,
    porcentaje: float,
    costo_kilo: float,
    descripcion: string,
}
export struct SistemaFND {
    user: UserFND,
    caja: CajaFND,
    configs: ConfigFND,
    ventas: [VentaFND],
    proveedores: [ProveedorFND],
    stash: [VentaFND],
    registro: [VentaFND],
}